include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_child_properties_last: true

analyzer:
  errors:
    unused_import: warning
